name: AutomatischeAutomatisierung

on: [push]

 # schedule:
 #   - cron: "*/2 * * * *"



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run scheduled task (hallo welt)
        run: echo 'hallo welt'
