name: AutomatischeAutomatisierung

on: 
 schedule:
    - cron: "7 13 * * *"



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run scheduled task (hallo welt)
        run: echo 'hallo welt'
